<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRphJdfc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRphJdfc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRphJdfc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRphJdfc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRphJdfc\App_KernelDevDebugContainer([
    'container.build_hash' => 'RphJdfc',
    'container.build_id' => '30ee1c82',
    'container.build_time' => 1687955558,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRphJdfc');
